# coding=UTF-8
# Copyright (c) 2025 Arfa Digital Consulting
# This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#    Benjamin Arfa - initial API and implementation
#

from pybirdai.process_steps.utils import Utils
from pybirdai.models.bird_meta_data_model import *
import os
from django.conf import settings
import ast
from datetime import datetime
import shutil
from pathlib import Path
from pybirdai.process_steps.ancrdt_transformation.filter_buildr import TransformationBuildr
from pybirdai.process_steps.ancrdt_transformation.ancrdt_transformation_func import (
    build_complete_module,
    create_output_class,
    create_output_table_class,
    create_union_item_class,
    create_base_class,
    create_union_table_class,
    create_join_class,
    create_join_table_class,
    create_filtered_class_pair
)

class CreatePythonTransformations:

    @staticmethod
    def _prepare_generated_file(file_path_str: str, logger) -> bool:
        """
        Prepare a file for generation by checking if it has been manually edited.

        Lifecycle logic:
        - If .py exists and .generated exists: compare them
          - If different: .py has manual edits, preserve it, delete .generated (will recreate)
          - If same: safe to regenerate
        - If .py exists but no .generated: first time generating, preserve current .py

        Args:
            file_path_str: Path to the .py file to generate
            logger: Logger instance

        Returns:
            bool: True if we should preserve existing .py file, False if safe to overwrite
        """
        file_path = Path(file_path_str)
        generated_path = Path(str(file_path_str) + '.generated')

        # If .py doesn't exist, nothing to preserve
        if not file_path.exists():
            return False

        # If .generated doesn't exist, this is first generation - preserve .py
        if not generated_path.exists():
            logger.info(f"Preserving existing {file_path.name} (no .generated base found)")
            return True

        # Both exist - compare them
        try:
            with open(file_path, 'r', encoding='utf-8') as f1:
                current_content = f1.read()
            with open(generated_path, 'r', encoding='utf-8') as f2:
                generated_content = f2.read()

            if current_content != generated_content:
                logger.info(f"Preserving manually edited {file_path.name}")
                # Delete old .generated, we'll create new one
                generated_path.unlink()
                return True
            else:
                # Files are identical, safe to regenerate
                logger.info(f"No edits detected in {file_path.name}, regenerating")
                return False
        except Exception as e:
            logger.error(f"Error comparing files: {e}")
            return True  # Preserve on error

    @staticmethod
    def _finalize_generated_file(file_path_str: str, preserve_original: bool, logger):
        """
        Finalize generation by creating .generated base copy.

        Args:
            file_path_str: Path to the generated .py file
            preserve_original: If True, original .py was preserved, copy to .generated
            logger: Logger instance
        """
        file_path = Path(file_path_str)
        generated_path = Path(str(file_path_str) + '.generated')

        try:
            if preserve_original:
                # Original .py was preserved with edits, new generation was skipped
                # Just log this state
                logger.info(f"Skipped generation of {file_path.name} (manual edits preserved)")
            else:
                # New file was generated, save as .generated base
                if file_path.exists():
                    shutil.copy2(file_path, generated_path)
                    logger.info(f"Created base reference: {generated_path.name}")
        except Exception as e:
            logger.error(f"Error finalizing generated file: {e}")

    @staticmethod
    def _write_generation_metadata(file, filename: str):
        """
        Write generation metadata header to file.

        Args:
            file: Open file handle
            filename: Name of the file being generated
        """
        timestamp = datetime.now().isoformat()
        file.write(f"# Generated: {timestamp}\n")
        file.write(f"# Generator: CreatePythonTransformations (ANCRDT Lifecycle)\n")
        file.write(f"# File: {filename}\n")
        file.write(f"# DO NOT EDIT THIS FILE DIRECTLY - Edit via web UI to preserve changes\n")
        file.write(f"# Base version saved as {filename}.generated\n\n")

    @staticmethod
    def create_python_joins(context, sdd_context,logger):
        '''
        Read in the transformation meta data and create python classes
        '''

        # CreatePythonTransformations.delete_generated_python_join_files(context)
        CreatePythonTransformations.create_output_classes( sdd_context,logger)
        CreatePythonTransformations.create_slice_classes(sdd_context,logger)
        # get all the cube_links for a report

    def create_output_classes(sdd_context,logger):
        """Generate output table classes for ANCRDT with lifecycle management (AST-based)"""

        file_path = sdd_context.output_directory + os.sep + 'generated_python_joins' + os.sep +  'ancrdt_output_tables.py'
        filename = 'ancrdt_output_tables.py'

        # Check if file has manual edits
        preserve = CreatePythonTransformations._prepare_generated_file(file_path, logger)
        if preserve:
            logger.info(f"Skipping generation of {filename} - manual edits detected")
            return

        print(f"DEBUG: cube_link_to_foreign_cube_map has {len(sdd_context.cube_link_to_foreign_cube_map)} entries")
        print(f"DEBUG: Keys: {list(sdd_context.cube_link_to_foreign_cube_map.keys())[:5]}")

        cube_link_to_foreign_cube_map__ = {
            rolc_id:cube_links
            for rolc_id, cube_links in sdd_context.cube_link_to_foreign_cube_map.items()
            if "ANCRDT" in rolc_id
        }
        print(f"DEBUG: Filtered to {len(cube_link_to_foreign_cube_map__)} ANCRDT entries")
        print(f"DEBUG: bird_cube_structure_item_dictionary has {len(sdd_context.bird_cube_structure_item_dictionary)} keys")
        print(f"DEBUG: Sample keys in bird_cube_structure_item_dictionary: {list(sdd_context.bird_cube_structure_item_dictionary.keys())[:10]}")

        # Collect all imports
        from pybirdai.process_steps.ancrdt_transformation.ancrdt_transformation_func.ast_builders import create_import
        imports = [
            create_import('pybirdai.process_steps.pybird.orchestration', ['Orchestration']),
            create_import('datetime', ['datetime']),
            create_import('pybirdai.annotations.decorators', ['lineage', 'track_table_init']),
        ]

        # Collect all classes
        all_classes = []

        for rolc_id, cube_links in cube_link_to_foreign_cube_map__.items():
            print(f"DEBUG: Processing rolc_id={rolc_id}, looking for key={rolc_id}")

            # Add relative import for logic module
            imports.append(create_import(f'.{rolc_id}_logic', None))  # from .{rolc_id}_logic import *

            if rolc_id in sdd_context.bird_cube_structure_item_dictionary:
                cube_structure_items = sdd_context.bird_cube_structure_item_dictionary[rolc_id]
                print(f"DEBUG: Found {len(cube_structure_items)} cube_structure_items for rolc_id={rolc_id}")
            else:
                print(f"ERROR: Key '{rolc_id}' not found in bird_cube_structure_item_dictionary")
                print(f"ERROR: Available ANCRDT keys: {[k for k in sdd_context.bird_cube_structure_item_dictionary.keys() if 'ANCRDT' in k]}")
                continue

            # Create output class using modular function
            output_class = create_output_class(rolc_id, cube_structure_items)
            all_classes.append(output_class)

            # Create output table class using modular function
            output_table_class = create_output_table_class(rolc_id)
            all_classes.append(output_table_class)

        # Build complete module with all classes
        source_code = build_complete_module(imports, all_classes, filename)

        # Write to file
        with open(file_path, 'w', encoding='utf-8') as file:
            file.write(source_code)

        # Finalize
        CreatePythonTransformations._finalize_generated_file(file_path, False, logger)

    def create_slice_classes(sdd_context, logger):
        """Generate slice/logic classes for ANCRDT with lifecycle management (AST-based)"""
        from pybirdai.process_steps.ancrdt_transformation.ancrdt_transformation_func.ast_builders import create_import
        from collections import defaultdict

        cube_link_to_foreign_cube_map__ = {
            rolc_id: cube_links
            for rolc_id, cube_links in sdd_context.cube_link_to_foreign_cube_map.items()
            if "ANCRDT" in rolc_id
        }

        for rolc_id, cube_links in cube_link_to_foreign_cube_map__.items():
            file_path = sdd_context.output_directory + os.sep + 'generated_python_joins' + os.sep + rolc_id + '_logic.py'
            filename = rolc_id + '_logic.py'

            # Check if file has manual edits
            preserve = CreatePythonTransformations._prepare_generated_file(file_path, logger)
            if preserve:
                logger.info(f"Skipping generation of {filename} - manual edits detected")
                continue

            # Collect imports
            imports = [
                create_import('pybirdai.models.bird_data_model', None),  # import *
                create_import('pybirdai.process_steps.pybird.orchestration', ['Orchestration']),
                create_import('pybirdai.process_steps.pybird.csv_converter', ['CSVConverter']),
                create_import('datetime', ['datetime']),
                create_import('pybirdai.annotations.decorators', ['lineage', 'track_table_init']),
            ]

            # Collect all classes for this rolc_id
            all_classes = []

            # Get cube structure items
            if rolc_id in sdd_context.bird_cube_structure_item_dictionary:
                cube_structure_items = sdd_context.bird_cube_structure_item_dictionary[rolc_id]
                print(f"DEBUG: Found {len(cube_structure_items)} cube_structure_items for rolc_id={rolc_id}")
            else:
                print(f"ERROR: Key '{rolc_id}' not found in bird_cube_structure_item_dictionary")
                cube_structure_items = []

            # 1. Create UnionItem class
            union_item_class = create_union_item_class(rolc_id, cube_structure_items)
            all_classes.append(union_item_class)

            # 2. Create Base class
            base_class = create_base_class(rolc_id, cube_structure_items)
            all_classes.append(base_class)

            # 3. Create UnionTable class (needs join information)
            cube_link_to_join_for_report_id_map__ = {
                join_for_rolc_id: cube_links_list
                for join_for_rolc_id, cube_links_list in sdd_context.cube_link_to_join_for_report_id_map.items()
                if rolc_id in join_for_rolc_id
            }
            logger.info(str(cube_link_to_join_for_report_id_map__))

            union_table_class = create_union_table_class(rolc_id, cube_link_to_join_for_report_id_map__, logger)
            all_classes.append(union_table_class)

            # 4. Create Join classes (one per unique join_identifier)
            # Collect ALL cube_structure_item_links from ALL cube_links with the same join_id
            join_classes_created = []
            for join_for_rolc_id, cube_links_list in cube_link_to_join_for_report_id_map__.items():
                report_and_join = join_for_rolc_id.split(':')
                join_id = report_and_join[1]
                if report_and_join[0] == rolc_id and join_id not in join_classes_created:
                    # Collect cube structure item links for ALL cube_links with this join_id
                    all_cube_structure_item_links = []
                    for cube_link in cube_links_list:
                        try:
                            cube_structure_item_links = sdd_context.cube_structure_item_link_to_cube_link_map[cube_link.cube_link_id]
                            all_cube_structure_item_links.extend(cube_structure_item_links)
                        except KeyError:
                            logger.info(f"No cube structure item links for cube_link: {cube_link.cube_link_id}")

                    join_class = create_join_class(rolc_id, join_id, all_cube_structure_item_links, logger)
                    all_classes.append(join_class)
                    join_classes_created.append(join_id)

            # 5. Create Join Table classes
            join_table_classes_created = []
            for join_for_rolc_id, cube_links_list in cube_link_to_join_for_report_id_map__.items():
                report_and_join = join_for_rolc_id.split(':')
                join_id = report_and_join[1]
                if report_and_join[0] == rolc_id and join_id not in join_table_classes_created:
                    # Collect cube structure item links for this join
                    all_cube_structure_item_links = []
                    for cube_link in cube_links_list:
                        try:
                            cube_structure_item_links = sdd_context.cube_structure_item_link_to_cube_link_map[cube_link.cube_link_id]
                            all_cube_structure_item_links.extend(cube_structure_item_links)
                        except KeyError:
                            logger.info(f"No cube structure item links for cube_link: {cube_link.cube_link_id}")

                    join_table_class = create_join_table_class(rolc_id, join_id, all_cube_structure_item_links, logger)
                    all_classes.append(join_table_class)
                    join_table_classes_created.append(join_id)

            # 6. Create filtered/aggregated classes
            filtered_classes_created = []
            for join_for_rolc_id, cube_links_list in cube_link_to_join_for_report_id_map__.items():
                report_and_join = join_for_rolc_id.split(':')
                join_id = report_and_join[1]
                if report_and_join[0] == rolc_id and join_id not in filtered_classes_created:
                    # Prefetch all CUBE_STRUCTURE_ITEM_LINK objects for all cube_links at once
                    all_cube_structure_item_links = CUBE_STRUCTURE_ITEM_LINK.objects.filter(
                        cube_link_id__in=cube_links_list
                    ).select_related(
                        'cube_link_id__primary_cube_id',
                        'cube_link_id__foreign_cube_id',
                        'primary_cube_variable_code__variable_id',
                        'foreign_cube_variable_code__variable_id'
                    )

                    # Group links by cube_link in memory
                    links_by_cube = defaultdict(list)
                    for link in all_cube_structure_item_links:
                        links_by_cube[link.cube_link_id].append(link)

                    # Generate filter for calc_ function
                    filter_assignments = []
                    filter_bool_vars = []

                    for cube_link in cube_links_list:
                        cube_structure_item_link_ids = links_by_cube.get(cube_link, [])
                        for cube_structure_item_link in cube_structure_item_link_ids:
                            assignments, bool_var_names = TransformationBuildr.define_filter_from_structure_link(
                                cube_structure_item_link.cube_structure_item_link_id
                            )
                            filter_assignments.extend(assignments)
                            filter_bool_vars.extend(bool_var_names)

                    if not filter_bool_vars:
                        continue

                    # Generate mapping methods
                    assignment_dicts = dict()
                    for cube_link in cube_links_list:
                        cube_structure_item_link_ids = links_by_cube.get(cube_link, [])
                        for cube_structure_item_link in cube_structure_item_link_ids:
                            assignment_dicts.update(TransformationBuildr.reverse_apply_member_links(
                                cube_structure_item_link.cube_structure_item_link_id
                            ))

                    # Create filtered class pair (table and item)
                    filtered_table, filtered_item = create_filtered_class_pair(
                        rolc_id,
                        join_id,
                        cube_structure_items,
                        cube_links_list,
                        links_by_cube,
                        assignment_dicts,
                        TransformationBuildr,
                        CUBE_STRUCTURE_ITEM_LINK,
                        logger
                    )
                    all_classes.append(filtered_table)
                    all_classes.append(filtered_item)
                    filtered_classes_created.append(join_id)

            # Build complete module
            source_code = build_complete_module(imports, all_classes, filename)

            # Write to file
            with open(file_path, 'w', encoding='utf-8') as file:
                file.write(source_code)

            # Finalize for this rolc_id
            CreatePythonTransformations._finalize_generated_file(file_path, False, logger)


    def delete_generated_python_join_files(context):
        base_dir = settings.BASE_DIR
        python_dir = os.path.join(base_dir, 'results',  'generated_python_joins')
        for file in os.listdir(python_dir):
            os.remove(os.path.join(python_dir, file))
