# coding=UTF-8
# Copyright (c) 2024 Bird Software Solutions Ltd
# This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#    Neil Mackenzie - initial API and implementation

"""
Django settings for birds_nest project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured


def _get_bool_env(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default

    return value.strip().lower() in {"1", "true", "yes", "on"}


def _get_list_env(name, default=None):
    value = os.environ.get(name)
    if value is None:
        return list(default or [])

    return [item.strip() for item in value.split(",") if item.strip()]


def _get_int_env(name, default):
    value = os.environ.get(name)
    if value is None:
        return default

    try:
        parsed = int(value)
    except ValueError as exc:
        raise ImproperlyConfigured(f"{name} must be an integer.") from exc

    if parsed < 0:
        raise ImproperlyConfigured(f"{name} must be zero or greater.")

    return parsed

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = _get_bool_env('DJANGO_DEBUG', default=True)
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-development-only-key'
    else:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is false.')

# Enable/disable debug data export for output layer mapping workflow
# Set to False in production to improve memory usage
DEBUG_EXPORT_ENABLED = False
LOCAL_ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '[::1]',
]
ALLOWED_HOSTS = _get_list_env(
    'DJANGO_ALLOWED_HOSTS',
    default=LOCAL_ALLOWED_HOSTS if DEBUG else LOCAL_ALLOWED_HOSTS,
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pybirdai',  # Make sure this line is present
]

MIDDLEWARE = [
    'pybirdai.middleware.security_middleware.SecurityHeadersMiddleware',
    'pybirdai.middleware.security_middleware.RequestLoggingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'pybirdai.middleware.security_middleware.SecurityErrorMiddleware',
]

ROOT_URLCONF = 'birds_nest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'pybirdai', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'birds_nest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

X_FRAME_OPTIONS = "SAMEORIGIN"

# Dynamic CSRF Trusted Origins configuration
# Supports environment variable for production: CSRF_TRUSTED_ORIGINS="https://example.com,https://www.example.com"
# Defaults to common localhost ports for development
CSRF_TRUSTED_ORIGINS = _get_list_env('CSRF_TRUSTED_ORIGINS', default=[
    'http://localhost:8000',
    'http://localhost:8001',
    'http://127.0.0.1:8000',
    'http://127.0.0.1:8001',
    'https://localhost:8000',
    'https://localhost:8001',
    'https://127.0.0.1:8000',
    'https://127.0.0.1:8001',
])

DATA_UPLOAD_MAX_NUMBER_FILES = _get_int_env('DJANGO_DATA_UPLOAD_MAX_NUMBER_FILES', 1000)
DATA_UPLOAD_MAX_MEMORY_SIZE = _get_int_env(
    'DJANGO_DATA_UPLOAD_MAX_MEMORY_SIZE',
    262144000 if DEBUG else 26214400,
)
FILE_UPLOAD_MAX_MEMORY_SIZE = _get_int_env('DJANGO_FILE_UPLOAD_MAX_MEMORY_SIZE', 2621440)

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
SECURE_SSL_REDIRECT = _get_bool_env('DJANGO_SECURE_SSL_REDIRECT', default=not DEBUG)
SESSION_COOKIE_SECURE = _get_bool_env('DJANGO_SESSION_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SECURE = _get_bool_env('DJANGO_CSRF_COOKIE_SECURE', default=not DEBUG)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = os.environ.get('DJANGO_SESSION_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_SAMESITE = os.environ.get('DJANGO_CSRF_COOKIE_SAMESITE', 'Lax')
SECURE_HSTS_SECONDS = int(
    os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '31536000' if not DEBUG else '0')
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _get_bool_env(
    'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS',
    default=not DEBUG,
)
SECURE_HSTS_PRELOAD = _get_bool_env('DJANGO_SECURE_HSTS_PRELOAD', default=False)

# # Logging Configuration for Security
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'verbose': {
#             'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
#             'style': '{',
#         },
#         'security': {
#             'format': 'SECURITY {levelname} {asctime} {message}',
#             'style': '{',
#         },
#     },
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#             'formatter': 'verbose',
#         },
#         'security_file': {
#             'class': 'logging.FileHandler',
#             'filename': 'security.log',
#             'formatter': 'security',
#         },
#         'error_file': {
#             'class': 'logging.FileHandler',
#             'filename': 'error.log',
#             'formatter': 'verbose',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['console', 'error_file'],
#             'level': 'INFO',
#             'propagate': True,
#         },
#         'pybirdai.middleware.security_middleware': {
#             'handlers': ['console', 'security_file'],
#             'level': 'WARNING',
#             'propagate': False,
#         },
#         'pybirdai.utils.secure_error_handling': {
#             'handlers': ['console', 'error_file'],
#             'level': 'ERROR',
#             'propagate': False,
#         },
#         'pybirdai': {
#             'handlers': ['console', 'error_file'],
#             'level': 'ERROR',
#             'propagate': True,
#         },
#     },
# }
