[project]
name = "birds-nest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.3",
    "pyecore>=0.15.1",
    "pylint>=3.3.1",
    "pyright>=1.1.389",
    "pytest>=8.3.3",
    "unidecode>=1.3.8",
]
