# Generated by Django 5.1.3 on 2025-05-19 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AXIS',
            fields=[
                ('axis_id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='axis_id')),
                ('code', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='code')),
                ('orientation', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='orientation')),
                ('order', models.BigIntegerField(blank=True, default=None, null=True, verbose_name='order')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='name')),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='description')),
                ('is_open_axis', models.BooleanField(blank=True, default=None, null=True, verbose_name='is_open_axis')),
            ],
            options={
                'verbose_name': 'AXIS',
                'verbose_name_plural': 'AXISs',
            },
        ),
        migrations.CreateModel(
            name='COMBINATION',
            fields=[
                ('combination_id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='combination_id')),
                ('code', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='code')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='name')),
                ('version', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='version')),
                ('valid_from', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_from')),
                ('valid_to', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_to')),
            ],
            options={
                'verbose_name': 'COMBINATION',
                'verbose_name_plural': 'COMBINATIONs',
            },
        ),
        migrations.CreateModel(
            name='CUBE',
            fields=[
                ('cube_id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='cube_id')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='name')),
                ('code', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='code')),
                ('cube_type', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='cube_type')),
                ('is_allowed', models.BooleanField(blank=True, default=None, null=True, verbose_name='is_allowed')),
                ('valid_from', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_from')),
                ('valid_to', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_to')),
                ('version', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='version')),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='description')),
                ('published', models.BooleanField(blank=True, default=None, null=True, verbose_name='published')),
                ('dataset_url', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='dataset_url')),
                ('filters', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='filters')),
                ('di_export', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='di_export')),
            ],
            options={
                'verbose_name': 'CUBE',
                'verbose_name_plural': 'CUBEs',
            },
        ),
        migrations.CreateModel(
            name='CUBE_STRUCTURE',
            fields=[
                ('cube_structure_id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='cube_structure_id')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='name')),
                ('code', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='code')),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='description')),
                ('valid_from', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_from')),
                ('valid_to', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_to')),
                ('version', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='version')),
            ],
            options={
                'verbose_name': 'CUBE_STRUCTURE',
                'verbose_name_plural': 'CUBE_STRUCTUREs',
            },
        ),
        migrations.CreateModel(
            name='FRAMEWORK',
            fields=[
                ('framework_id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='framework_id')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='name')),
                ('code', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='code')),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='description')),
                ('framework_type', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='framework_type')),
                ('reporting_population', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='reporting_population')),
                ('other_links', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='other_links')),
                ('order', models.BigIntegerField(blank=True, default=None, null=True, verbose_name='order')),
                ('framework_status', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='framework_status')),
            ],
            options={
                'verbose_name': 'FRAMEWORK',
                'verbose_name_plural': 'FRAMEWORKs',
            },
        ),
        migrations.CreateModel(
            name='MAINTENANCE_AGENCY',
            fields=[
                ('maintenance_agency_id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='maintenance_agency_id')),
                ('code', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='code')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='name')),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'MAINTENANCE_AGENCY',
                'verbose_name_plural': 'MAINTENANCE_AGENCYs',
            },
        ),
        migrations.CreateModel(
            name='AXIS_ORDINATE',
            fields=[
                ('axis_ordinate_id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='axis_ordinate_id')),
                ('is_abstract_header', models.BooleanField(blank=True, default=None, null=True, verbose_name='is_abstract_header')),
                ('code', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='code')),
                ('order', models.BigIntegerField(blank=True, default=None, null=True, verbose_name='order')),
                ('level', models.BigIntegerField(blank=True, default=None, null=True, verbose_name='level')),
                ('path', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='path')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='name')),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='description')),
                ('axis_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.axis')),
                ('parent_axis_ordinate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.axis_ordinate')),
            ],
            options={
                'verbose_name': 'AXIS_ORDINATE',
                'verbose_name_plural': 'AXIS_ORDINATEs',
            },
        ),
        migrations.CreateModel(
            name='CUBE_LINK',
            fields=[
                ('cube_link_id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='cube_link_id')),
                ('code', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='code')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='name')),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='description')),
                ('valid_from', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_from')),
                ('valid_to', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_to')),
                ('version', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='version')),
                ('order_relevance', models.BigIntegerField(blank=True, default=None, null=True, verbose_name='order_relevance')),
                ('cube_link_type', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='cube_link_type')),
                ('join_identifier', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='join_identifier')),
                ('foreign_cube_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreign_cube_in_cube_link', to='pybirdai.cube')),
                ('primary_cube_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_cube_in_cube_link', to='pybirdai.cube')),
                ('maintenance_agency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.maintenance_agency')),
            ],
            options={
                'verbose_name': 'CUBE_LINK',
                'verbose_name_plural': 'CUBE_LINKs',
            },
        ),
        migrations.AddField(
            model_name='cube',
            name='cube_structure_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.cube_structure'),
        ),
        migrations.CreateModel(
            name='CUBE_STRUCTURE_ITEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cube_variable_code', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='cube_variable_code')),
                ('role', models.CharField(blank=True, choices=[('O', 'O'), ('A', 'A'), ('D', 'D')], default=None, max_length=1000, null=True, verbose_name='role')),
                ('order', models.BigIntegerField(blank=True, default=None, null=True, verbose_name='order')),
                ('dimension_type', models.CharField(blank=True, choices=[('B', 'B'), ('M', 'M'), ('T', 'T'), ('U', 'U')], default=None, max_length=1000, null=True, verbose_name='dimension_type')),
                ('is_flow', models.BooleanField(blank=True, default=None, null=True, verbose_name='is_flow')),
                ('is_mandatory', models.BooleanField(blank=True, default=None, null=True, verbose_name='is_mandatory')),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='description')),
                ('is_implemented', models.BooleanField(blank=True, default=None, null=True, verbose_name='is_implemented')),
                ('is_identifier', models.BooleanField(blank=True, default=None, null=True, verbose_name='is_identifier')),
                ('cube_structure_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.cube_structure')),
            ],
            options={
                'verbose_name': 'CUBE_STRUCTURE_ITEM',
                'verbose_name_plural': 'CUBE_STRUCTURE_ITEMs',
            },
        ),
        migrations.CreateModel(
            name='CUBE_STRUCTURE_ITEM_LINK',
            fields=[
                ('cube_structure_item_link_id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='cube_structure_item_link_id')),
                ('cube_link_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.cube_link')),
                ('foreign_cube_variable_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreign_cube_variable_code', to='pybirdai.cube_structure_item')),
                ('primary_cube_variable_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_cube_variable_code', to='pybirdai.cube_structure_item')),
            ],
            options={
                'verbose_name': 'CUBE_STRUCTURE_ITEM_LINK',
                'verbose_name_plural': 'CUBE_STRUCTURE_ITEM_LINKs',
            },
        ),
        migrations.CreateModel(
            name='CUBE_TO_COMBINATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combination_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.combination')),
                ('cube_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.cube')),
            ],
            options={
                'verbose_name': 'CUBE_TO_COMBINATION',
                'verbose_name_plural': 'CUBE_TO_COMBINATIONs',
            },
        ),
        migrations.AddField(
            model_name='cube',
            name='framework_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.framework'),
        ),
        migrations.AddField(
            model_name='framework',
            name='maintenance_agency_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.maintenance_agency'),
        ),
        migrations.CreateModel(
            name='FACET_COLLECTION',
            fields=[
                ('code', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='code')),
                ('facet_id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='facet_id')),
                ('facet_value_type', models.CharField(blank=True, choices=[('BigInteger', 'BigInteger'), ('Boolean', 'Boolean'), ('DateTime', 'DateTime'), ('Day_MonthDay_Month', 'DayMonthDayMonth'), ('Decimal', 'Decimal'), ('Double', 'Double'), ('Duration', 'Duration'), ('Float', 'Float'), ('GregorianDay', 'GregorianDay'), ('GregorianMonth', 'GregorianMonth'), ('GregorianYear', 'GregorianYear'), ('Integer', 'Integer'), ('Long', 'Long'), ('Short', 'Short'), ('String', 'String'), ('Time', 'Time'), ('URI', 'URI')], default=None, max_length=1000, null=True, verbose_name='facet_value_type')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='name')),
                ('maintenance_agency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.maintenance_agency')),
            ],
            options={
                'verbose_name': 'FACET_COLLECTION',
                'verbose_name_plural': 'FACET_COLLECTIONs',
            },
        ),
        migrations.CreateModel(
            name='DOMAIN',
            fields=[
                ('domain_id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='domain_id')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='name')),
                ('is_enumerated', models.BooleanField(blank=True, default=None, null=True, verbose_name='is_enumerated')),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='description')),
                ('data_type', models.CharField(blank=True, choices=[('BigInteger', 'BigInteger'), ('Boolean', 'Boolean'), ('DateTime', 'DateTime'), ('Day_MonthDay_Month', 'DayMonthDayMonth'), ('Decimal', 'Decimal'), ('Double', 'Double'), ('Duration', 'Duration'), ('Float', 'Float'), ('GregorianDay', 'GregorianDay'), ('GregorianMonth', 'GregorianMonth'), ('GregorianYear', 'GregorianYear'), ('Integer', 'Integer'), ('Long', 'Long'), ('Short', 'Short'), ('String', 'String'), ('Time', 'Time'), ('URI', 'URI')], default=None, max_length=1000, null=True, verbose_name='data_type')),
                ('code', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='code')),
                ('is_reference', models.BooleanField(blank=True, default=None, null=True, verbose_name='is_reference')),
                ('facet_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.facet_collection')),
                ('maintenance_agency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.maintenance_agency')),
            ],
            options={
                'verbose_name': 'DOMAIN',
                'verbose_name_plural': 'DOMAINs',
            },
        ),
        migrations.AddField(
            model_name='cube_structure',
            name='maintenance_agency_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.maintenance_agency'),
        ),
        migrations.AddField(
            model_name='cube',
            name='maintenance_agency_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.maintenance_agency'),
        ),
        migrations.AddField(
            model_name='combination',
            name='maintenance_agency_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.maintenance_agency'),
        ),
        migrations.CreateModel(
            name='MAPPING_DEFINITION',
            fields=[
                ('mapping_id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='mapping_id')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='name')),
                ('mapping_type', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='mapping_type')),
                ('code', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='code')),
                ('algorithm', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='algorithm')),
                ('maintenance_agency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.maintenance_agency')),
            ],
            options={
                'verbose_name': 'MAPPING_DEFINITION',
                'verbose_name_plural': 'MAPPING_DEFINITIONs',
            },
        ),
        migrations.CreateModel(
            name='MAPPING_TO_CUBE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cube_mapping_id', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='cube_mapping_id')),
                ('valid_from', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_from')),
                ('valid_to', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_to')),
                ('mapping_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.mapping_definition')),
            ],
            options={
                'verbose_name': 'MAPPING_TO_CUBE',
                'verbose_name_plural': 'MAPPING_TO_CUBEs',
            },
        ),
        migrations.CreateModel(
            name='MEMBER',
            fields=[
                ('member_id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='member_id')),
                ('code', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='code')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='name')),
                ('description', models.CharField(blank=True, default=None, max_length=3000, null=True, verbose_name='description')),
                ('domain_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.domain')),
                ('maintenance_agency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.maintenance_agency')),
            ],
            options={
                'verbose_name': 'MEMBER',
                'verbose_name_plural': 'MEMBERs',
            },
        ),
        migrations.AddField(
            model_name='cube_structure_item',
            name='member_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.member'),
        ),
        migrations.CreateModel(
            name='MEMBER_HIERARCHY',
            fields=[
                ('member_hierarchy_id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='member_hierarchy_id')),
                ('code', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='code')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='name')),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='description')),
                ('is_main_hierarchy', models.BooleanField(blank=True, default=None, null=True, verbose_name='is_main_hierarchy')),
                ('domain_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.domain')),
                ('maintenance_agency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.maintenance_agency')),
            ],
            options={
                'verbose_name': 'MEMBER_HIERARCHY',
                'verbose_name_plural': 'MEMBER_HIERARCHYs',
            },
        ),
        migrations.CreateModel(
            name='MEMBER_HIERARCHY_NODE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.BigIntegerField(blank=True, default=None, null=True, verbose_name='level')),
                ('comparator', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='comparator')),
                ('operator', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='operator')),
                ('valid_from', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_from')),
                ('valid_to', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_to')),
                ('member_hierarchy_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.member_hierarchy')),
                ('member_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_id_in_hierarchy', to='pybirdai.member')),
                ('parent_member_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_member_id', to='pybirdai.member')),
            ],
            options={
                'verbose_name': 'MEMBER_HIERARCHY_NODE',
                'verbose_name_plural': 'MEMBER_HIERARCHY_NODEs',
            },
        ),
        migrations.CreateModel(
            name='MEMBER_LINK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_linked', models.BooleanField(blank=True, default=None, null=True, verbose_name='is_linked')),
                ('valid_from', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_from')),
                ('valid_to', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_to')),
                ('cube_structure_item_link_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.cube_structure_item_link')),
                ('foreign_member_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreign_member', to='pybirdai.member')),
                ('primary_member_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_member', to='pybirdai.member')),
            ],
            options={
                'verbose_name': 'MEMBER_LINK',
                'verbose_name_plural': 'MEMBER_LINKs',
            },
        ),
        migrations.CreateModel(
            name='MEMBER_MAPPING',
            fields=[
                ('member_mapping_id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='member_mapping_id')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='name')),
                ('code', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='code')),
                ('maintenance_agency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.maintenance_agency')),
            ],
            options={
                'verbose_name': 'MEMBER_MAPPING',
                'verbose_name_plural': 'MEMBER_MAPPINGs',
            },
        ),
        migrations.AddField(
            model_name='mapping_definition',
            name='member_mapping_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.member_mapping'),
        ),
        migrations.CreateModel(
            name='SUBDOMAIN',
            fields=[
                ('subdomain_id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='subdomain_id')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='name')),
                ('is_listed', models.BooleanField(blank=True, default=None, null=True, verbose_name='is_listed')),
                ('code', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='code')),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='description')),
                ('is_natural', models.BooleanField(blank=True, default=None, null=True, verbose_name='is_natural')),
                ('domain_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.domain')),
                ('facet_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.facet_collection')),
                ('maintenance_agency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.maintenance_agency')),
            ],
            options={
                'verbose_name': 'SUBDOMAIN',
                'verbose_name_plural': 'SUBDOMAINs',
            },
        ),
        migrations.AddField(
            model_name='cube_structure_item',
            name='subdomain_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.subdomain'),
        ),
        migrations.CreateModel(
            name='SUBDOMAIN_ENUMERATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_from')),
                ('valid_to', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_to')),
                ('order', models.BigIntegerField(blank=True, default=None, null=True, verbose_name='order')),
                ('member_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.member')),
                ('subdomain_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.subdomain')),
            ],
            options={
                'verbose_name': 'SUBDOMAIN_ENUMERATION',
                'verbose_name_plural': 'SUBDOMAIN_ENUMERATIONs',
            },
        ),
        migrations.CreateModel(
            name='TABLE',
            fields=[
                ('table_id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='table_id')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='name')),
                ('code', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='code')),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='description')),
                ('version', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='version')),
                ('valid_from', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_from')),
                ('valid_to', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_to')),
                ('maintenance_agency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.maintenance_agency')),
            ],
            options={
                'verbose_name': 'TABLE',
                'verbose_name_plural': 'TABLEs',
            },
        ),
        migrations.AddField(
            model_name='axis',
            name='table_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.table'),
        ),
        migrations.CreateModel(
            name='TABLE_CELL',
            fields=[
                ('cell_id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='cell_id')),
                ('is_shaded', models.BooleanField(blank=True, default=None, null=True, verbose_name='is_shaded')),
                ('table_cell_combination_id', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='table_cell_combination_id')),
                ('system_data_code', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='system_data_code')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='name')),
                ('table_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.table')),
            ],
            options={
                'verbose_name': 'TABLE_CELL',
                'verbose_name_plural': 'TABLE_CELLs',
            },
        ),
        migrations.CreateModel(
            name='CELL_POSITION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis_ordinate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.axis_ordinate')),
                ('cell_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.table_cell')),
            ],
            options={
                'verbose_name': 'CELL_POSITION',
                'verbose_name_plural': 'CELL_POSITIONs',
            },
        ),
        migrations.CreateModel(
            name='VARIABLE',
            fields=[
                ('variable_id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='variable_id')),
                ('code', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='code')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='name')),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='description')),
                ('primary_concept', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='primary_concept')),
                ('is_decomposed', models.BooleanField(blank=True, default=None, null=True, verbose_name='is_decomposed')),
                ('domain_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.domain')),
                ('maintenance_agency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.maintenance_agency')),
            ],
            options={
                'verbose_name': 'VARIABLE',
                'verbose_name_plural': 'VARIABLEs',
            },
        ),
        migrations.CreateModel(
            name='ORDINATE_ITEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_hierarchy_valid_from', models.DateTimeField(blank=True, default=None, null=True, verbose_name='member_hierarchy_valid_from')),
                ('is_starting_member_included', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='is_starting_member_included')),
                ('axis_ordinate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.axis_ordinate')),
                ('member_hierarchy_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.member_hierarchy')),
                ('member_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.member')),
                ('starting_member_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starting_member_id', to='pybirdai.member')),
                ('variable_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.variable')),
            ],
            options={
                'verbose_name': 'ORDINATE_ITEM',
                'verbose_name_plural': 'ORDINATE_ITEMs',
            },
        ),
        migrations.CreateModel(
            name='MEMBER_MAPPING_ITEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_mapping_row', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='row')),
                ('is_source', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='is_source')),
                ('valid_from', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_from')),
                ('valid_to', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_to')),
                ('member_hierarchy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.member_hierarchy')),
                ('member_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.member')),
                ('member_mapping_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.member_mapping')),
                ('variable_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.variable')),
            ],
            options={
                'verbose_name': 'MEMBER_MAPPING_ITEM',
                'verbose_name_plural': 'MEMBER_MAPPING_ITEMs',
            },
        ),
        migrations.AddField(
            model_name='cube_structure_item',
            name='attribute_associated_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_associated_variable', to='pybirdai.variable'),
        ),
        migrations.AddField(
            model_name='cube_structure_item',
            name='variable_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.variable'),
        ),
        migrations.AddField(
            model_name='combination',
            name='metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.variable'),
        ),
        migrations.CreateModel(
            name='VARIABLE_MAPPING',
            fields=[
                ('variable_mapping_id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='variable_mapping_id')),
                ('code', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='code')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='name')),
                ('maintenance_agency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.maintenance_agency')),
            ],
            options={
                'verbose_name': 'VARIABLE_MAPPING',
                'verbose_name_plural': 'VARIABLE_MAPPINGs',
            },
        ),
        migrations.AddField(
            model_name='mapping_definition',
            name='variable_mapping_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.variable_mapping'),
        ),
        migrations.CreateModel(
            name='VARIABLE_MAPPING_ITEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_source', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='is_source')),
                ('valid_from', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_from')),
                ('valid_to', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_to')),
                ('variable_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.variable')),
                ('variable_mapping_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.variable_mapping')),
            ],
            options={
                'verbose_name': 'VARIABLE_MAPPING_ITEM',
                'verbose_name_plural': 'VARIABLE_MAPPING_ITEMs',
            },
        ),
        migrations.CreateModel(
            name='VARIABLE_SET',
            fields=[
                ('variable_set_id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='variable_set_id')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='name')),
                ('code', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='code')),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='description')),
                ('maintenance_agency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variable_set_maintenance_agency', to='pybirdai.maintenance_agency')),
            ],
            options={
                'verbose_name': 'VARIABLE_SET',
                'verbose_name_plural': 'VARIABLE_SETs',
            },
        ),
        migrations.AddField(
            model_name='cube_structure_item',
            name='variable_set_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.variable_set'),
        ),
        migrations.CreateModel(
            name='COMBINATION_ITEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combination_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.combination')),
                ('member_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.member')),
                ('member_hierarchy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.member_hierarchy')),
                ('subdomain_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.subdomain')),
                ('variable_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.variable')),
                ('variable_set_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.variable_set')),
            ],
            options={
                'verbose_name': 'COMBINATION_ITEM',
                'verbose_name_plural': 'COMBINATION_ITEMs',
            },
        ),
        migrations.CreateModel(
            name='VARIABLE_SET_ENUMERATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_from')),
                ('valid_to', models.DateTimeField(blank=True, default=None, null=True, verbose_name='valid_to')),
                ('is_flow', models.BooleanField(blank=True, default=None, null=True, verbose_name='is_flow')),
                ('order', models.BigIntegerField(blank=True, default=None, null=True, verbose_name='order')),
                ('subdomain_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.subdomain')),
                ('variable_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.variable')),
                ('variable_set_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pybirdai.variable_set')),
            ],
            options={
                'verbose_name': 'VARIABLE_SET_ENUMERATION',
                'verbose_name_plural': 'VARIABLE_SET_ENUMERATIONs',
            },
        ),
    ]
