# coding=UTF-8
# Copyright (c) 2025 Bird Software Solutions Ltd
# This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#    Neil Mackenzie - initial API and implementation
#    Benjamin Arfa - improvements
#
class SimpleContext(object):
    '''
       
    '''
    def get_all_related_tables(self):
        all_related_tables = [
            'SCRTY_EXCHNG_TRDBL_DRVTV', 'CRDT_FCLTY', 'CRDT_FCLTY_ENTTY_RL_ASSGNMNT', 'INSTRMNT', 'INSTRMNT_RL',
            'NN_FNNCL_ASST_NN_FNNCL_LBLTY', 'CSH_HND', 'PRTY', 'SCRTY_EXCHNG_TRDBL_DRVTV_PSTN',
            'LNG_SCRTY_PSTN_PRDNTL_PRTFL_ASSGNMNT', 'LNG_SCRTY_PSTN_PRDNTL_PRTFL_ASSGNMNT_ACCNTNG_CLSSFCTN_FNNCL_ASSTS_ASSGNMNT',
            'CLLTRL', 'INSTRMNT_ENTTY_RL_ASSGNMNT', 'FNNCL_CNTRCT', 'ENTTY_RL', 'FNDMNTL_RVW_TRDNG_BK_STNDRD_APPRCH_RSK_MSR',
            'RSK_FAC_SA', 'ASST_PL', 'ASST_PL_DBT_SCRTY_PSTN_ASSGNMNT', 'ASST_PL_EQT_INSTRMNT_NT_SCRT_ASSGNMNT',
            'ASST_PL_LN_ASSGNMNT', 'BLNC_SHT_NTTNG', 'CLLTRL_NN_FNNCL_ASST_ASSGNMNT', 'CRDT_FCLTY_CLLTRL_ASSGNMNT',
            'CRDT_FCLTY_CLLTRL_RCVD_INSTRMNT_ASSGNMNT', 'CRDT_RSK_MTGTN_ASSGNMNT', 'CRDT_TRNSFR_OTHR_SCRTSTN_CVRD_BND_PRGRM',
            'CVRD_BND_ISSNC', 'CVRD_BND_PRGRM', 'DBT_SCRTY_ISSD', 'DBT_SCRTY_ISSD_TRDTNL_SCRTSTN_ASSGNMNT',
            'EQT_INSTRMNT_LG_EQT_INSTRMNT_NT_SCRT_ASSGNMNT', 'ETD_LBLTY_PSTN_SNTHTC_SCRTSTN_ASSGNMNT',
            'EXCHNG_TRDBL_DRVTV_PSTN', 'FNDMNTL_RVW_TRDNG_BK_STNDRD_APPRCH_RSK_MSR_ETD_PSTNS',
            'FNDMNTL_RVW_TRDNG_BK_STNDRD_APPRCH_RSK_MSR_FR_SCRTY_PSTNS', 'FNDMNTL_RVW_TRDNG_BK_STNDRD_APPRCH_RSK_MSR_OTC_PSTNS',
            'FNNCL_GRNT_INSTRMNT_DBT_SCRT_DBT_SCRTY_ASSGNMNT', 'GRP', 'GRP_CLNTS_KY_MNGMNT_PRSNLL_ASSGNMNT',
            'IMMDT_PRNT_ENTRPRS_ASSGNMNT', 'INSTRMNT_CLLTRL_RCVD_INSTRMNT_ASSGNMNT', 'INSTRMNT_HDGD_EXCHNG_TRDBL_DRVTV',
            'INSTRMNT_HDGD_OTC_DRVTV', 'INSTRMNT_PRTCN_ARRNGMNT_ASSGNMNT', 'INTRNL_GRP_KY_MNGMNT_PRSNLL_ASSGNMNT',
            'INTRNL_GRP_RL', 'INTRST_RT_RSK_HDG_PRTFL', 'KB_PR_BCKT', 'LN_AND_ADVNC_LG_LN_AND_ADVNC_ASSGNMNT',
            'LN_EXCLDNG_RPRCHS_AGRMNT_CLLTRL_ASSGNMNT', 'LNG_NN_NGTBL_SCRTY_PSTN_CLLTRL_ASSGNMNT',
            'LNG_SCRTY_PSTN_PRDNTL_PRTFL_ASSGNMNT_RSK_DT', 'LNKD_ENTRPRS_ASSGNMNT', 'MSTR_AGRMNT',
            'MSTR_AGRMNT_ENTTY_RL_ASSGNMNT', 'MSTR_AGRMNT_FNNCL_CNTRCT_ASSGNMNT', 'NN_FNNCL_ASST', 'NN_FNNCL_LBLTY',
            'NTRL_PRSN_KY_MNGMNT_PRSNLL_ASSGNMNT', 'OFF_BLNC_INSTRMNT_CLLTRL_ASSGNMNT',
            'OTC_DRVTV_INSTRMNT_SNTHTC_SCRTSTN_ASSGNMNT', 'OTHR_PRTY_ID', 'PRTCTN_ARRNGMNT', 'PRTCTN_PRTCTN_PRVD_ASSGNMNT',
            'PRTNR_ENTRPRS_ASSGNMNT', 'PRTY_CD', 'PRTY_PRVS_PRD_DT', 'RPRCHS_AGRMNT_CMPNNT', 'RTNG_AGNCY', 'RTNG_GRD',
            'RTNG_GRD_CNTRY_ASSGNMNT', 'RTNG_GRD_ISS_BSD_RTNG_SSTM_DBT_SCRTY_ASSGNMNT', 'RTNG_SYSTM', 'RTNG_SYSTM_APPLD_LGL_PRSN',
            'SBSDRY_JNT_VNTR_ASSCT_OTHR_ORGNSTN_ASSGNMNT', 'SCRTY_ENTTY_RL_ASSGNMNT', 'SCRTY_HDGD_EXCHNG_TRDBL_DRVTV',
            'SCRTY_PSTN', 'SCRTY_PSTN_HDGD_OTC_DRVTV', 'SCRTY_SCRTY_RPRCHS_AGRMNT_CMPNNT_ASSGNMNT',
            'SCTRY_BRRWNG_LNDNG_TRNSCTN_INCLDNG_CSH_CLLTRL', 'SHRT_SCRTY_PSTN_PRDNTL_PRTFL_ASSGNMNT', 'SNTHTC_SCRTSTN',
            'SYNDCTD_CNTRCT', 'TRDTNL_SCRTSTN', 'TRNCH_SYNTHTC_SCRTSTN_WTHT_SSPE_DPST',
            'TRNCH_SYNTHTC_SCRTSTN_WTHT_SSPE_FNNCL_GRNT', 'TRNCH_TRDTNL_SCRTSTN'
        ]
                               
                               
        return all_related_tables
    
