# coding=UTF-8
# Copyright (c) 2026 Bird Software Solutions Ltd
# This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#    Neil Mackenzie - initial API and implementation
#
"""
Push a local test suite back to the repository it was fetched from.

A suite is fetched into ``tests/<repository name>/`` with the repository's own
layout intact (see ``CloneRepoService.setup_test_suite_files``), so a file's
path below that directory is its path in the repository. That mapping is what
lets edited test data and edited expected results be pushed back.

The push always goes to a new branch, named by the user, in a single commit. No
existing branch is moved, so a mistaken push costs nothing more than deleting
the branch again.

Changes are worked out against the base branch rather than assumed: a file is
compared by its Git blob hash, so only what actually differs is uploaded, and a
file the repository still has but the local suite no longer does is deleted in
the commit.

Files that are not part of the suite's source are left out of the comparison
entirely - caches, hidden files, and the results of local test runs - so they
are neither pushed nor treated as deletions.
"""

import base64
import hashlib
import logging
import os
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

#: Directory of test run output inside a suite. Regenerated by every run, so it
#: is not part of what a suite change means.
TEST_RESULTS_RELATIVE_PATH = "tests/test_results"

#: Directory and file names that belong to a checkout rather than the suite.
EXCLUDED_DIRECTORY_NAMES = {"__pycache__", ".git", ".pytest_cache", "node_modules"}
EXCLUDED_FILE_SUFFIXES = (".pyc", ".pyo", ".pyd")

#: Root-level files the fetch never copies locally. Their absence locally says
#: nothing about the repository, so they are never deleted.
UNTRACKED_ROOT_FILE_NAMES = {
    "readme.md",
    "readme.txt",
    "readme",
    "license",
    "license.md",
    "license.txt",
    "notice",
    "notice.md",
    ".gitignore",
    ".gitattributes",
}

#: Upload limits. The GitHub blob API takes base64 in a JSON body, so a large
#: file is a request that will fail slowly rather than one that will succeed.
MAX_FILE_BYTES = 25 * 1024 * 1024
MAX_TOTAL_UPLOAD_BYTES = 100 * 1024 * 1024

GITHUB_FILE_MODE = "100644"


class TestSuitePublishError(RuntimeError):
    """A push that cannot be completed, described in terms the user can act on."""


@dataclass(frozen=True)
class SuiteFile:
    """One local file of a suite, with the path it occupies in the repository."""

    local_path: str
    repo_path: str
    blob_sha: str
    size: int


@dataclass
class PublishPlan:
    """What a push would change, worked out against the base branch."""

    suite_name: str
    repository_url: str
    owner: str
    repo: str
    base_branch: str
    base_commit_sha: str
    base_tree_sha: str
    added: List[str] = field(default_factory=list)
    modified: List[str] = field(default_factory=list)
    deleted: List[str] = field(default_factory=list)
    unchanged_count: int = 0
    upload_bytes: int = 0
    files_by_path: Dict[str, SuiteFile] = field(default_factory=dict)

    @property
    def has_changes(self) -> bool:
        return bool(self.added or self.modified or self.deleted)

    def as_dict(self) -> Dict:
        return {
            "suite": self.suite_name,
            "repository_url": self.repository_url,
            "base_branch": self.base_branch,
            "base_commit_sha": self.base_commit_sha,
            "added": self.added,
            "modified": self.modified,
            "deleted": self.deleted,
            "added_count": len(self.added),
            "modified_count": len(self.modified),
            "deleted_count": len(self.deleted),
            "unchanged_count": self.unchanged_count,
            "has_changes": self.has_changes,
        }


def git_blob_sha(content: bytes) -> str:
    """The hash Git would store this content under, for comparing with a remote tree."""
    header = f"blob {len(content)}\0".encode("utf-8")
    return hashlib.sha1(header + content).hexdigest()


def _is_tracked_repo_path(repo_path: str, include_test_results: bool) -> bool:
    """
    Whether a repository path takes part in the comparison.

    Applied to both sides: a path that is not tracked is never uploaded, and
    never counted as deleted when the local suite does not hold it.
    """
    parts = repo_path.split("/")
    if any(part in EXCLUDED_DIRECTORY_NAMES or part.startswith(".") for part in parts[:-1]):
        return False

    file_name = parts[-1]
    if file_name.startswith(".") or file_name.endswith(EXCLUDED_FILE_SUFFIXES):
        return False

    if len(parts) == 1 and file_name.lower() in UNTRACKED_ROOT_FILE_NAMES:
        return False

    if not include_test_results and repo_path.startswith(f"{TEST_RESULTS_RELATIVE_PATH}/"):
        return False

    return True


def collect_suite_files(suite_directory: str, include_test_results: bool = False) -> List[SuiteFile]:
    """
    Read every file of a local suite that takes part in a push.

    Args:
        suite_directory: Absolute path of the suite directory under ``tests/``
        include_test_results: Push the output of local test runs as well

    Returns:
        The suite's files, sorted by their repository path

    Raises:
        TestSuitePublishError: a file is too large to upload
    """
    files: List[SuiteFile] = []

    for current_directory, sub_directories, file_names in os.walk(suite_directory):
        sub_directories[:] = sorted(
            name
            for name in sub_directories
            if name not in EXCLUDED_DIRECTORY_NAMES and not name.startswith(".")
        )

        for file_name in sorted(file_names):
            local_path = os.path.join(current_directory, file_name)
            repo_path = os.path.relpath(local_path, suite_directory).replace(os.sep, "/")
            if not _is_tracked_repo_path(repo_path, include_test_results):
                continue

            try:
                with open(local_path, "rb") as handle:
                    content = handle.read(MAX_FILE_BYTES + 1)
            except OSError as exc:
                logger.warning("Skipping unreadable suite file %s: %s", repo_path, exc)
                continue

            if len(content) > MAX_FILE_BYTES:
                raise TestSuitePublishError(
                    f"'{repo_path}' is larger than {MAX_FILE_BYTES // (1024 * 1024)} MB and cannot be pushed."
                )

            files.append(
                SuiteFile(
                    local_path=local_path,
                    repo_path=repo_path,
                    blob_sha=git_blob_sha(content),
                    size=len(content),
                )
            )

    return sorted(files, key=lambda suite_file: suite_file.repo_path)


class TestSuitePublisher:
    """
    Compare a local test suite with a GitHub repository, and push the difference.

    The GitHub calls go through :class:`GitHubIntegrationService`, which
    validates every owner, repository, ref and path component before it reaches
    a URL.
    """

    def __init__(self, repository_url: str, github_token: str):
        from pybirdai.api.workflow_api import GitHubIntegrationService

        if not (github_token or "").strip():
            raise TestSuitePublishError("A GitHub token is required to push a test suite.")

        self.repository_url = (repository_url or "").strip()
        self.service = GitHubIntegrationService(github_token.strip())

        owner, repo = self.service._parse_github_url(self.repository_url)
        if not owner or not repo:
            raise TestSuitePublishError("The repository must be a GitHub URL, like https://github.com/owner/repo.")

        self.owner = owner
        self.repo = repo

    # -- GitHub calls ----------------------------------------------------

    def _request(self, method: str, *parts: str, **kwargs):
        try:
            return self.service._request_github_repo_api(method, self.owner, self.repo, *parts, **kwargs)
        except ValueError as exc:
            raise TestSuitePublishError(str(exc)) from exc
        except Exception as exc:
            logger.error("GitHub request failed for %s/%s: %s", self.owner, self.repo, exc)
            raise TestSuitePublishError("Could not reach GitHub.") from exc

    @staticmethod
    def _describe_failure(response, action: str) -> str:
        """Turn a GitHub status code into something the user can act on."""
        if response.status_code in (401, 403):
            return f"The GitHub token is not allowed to {action}."
        if response.status_code == 404:
            return f"Could not {action}: the repository or branch was not found, or the token cannot see it."
        if response.status_code == 422:
            return f"GitHub rejected the request to {action}."
        return f"GitHub returned {response.status_code} when asked to {action}."

    def _validate_branch(self, branch: str, field_name: str = "branch name") -> str:
        """Check a branch name here, so a typed name is answered rather than crashed on."""
        try:
            return self.service._validate_github_ref(branch, field_name)
        except ValueError as exc:
            raise TestSuitePublishError(f"That is not a name Git can use as a {field_name}.") from exc

    def _ref_parts(self, branch: str) -> Tuple[str, ...]:
        """The path components of a ref, so a branch name with '/' stays a path."""
        branch = self._validate_branch(branch)
        return ("git", "ref", "heads", *branch.split("/"))

    def branch_exists(self, branch: str) -> bool:
        response = self._request("GET", *self._ref_parts(branch))
        if response.status_code == 200:
            return True
        if response.status_code == 404:
            return False
        raise TestSuitePublishError(self._describe_failure(response, "read the repository's branches"))

    def _branch_commit_sha(self, branch: str) -> str:
        response = self._request("GET", *self._ref_parts(branch))
        if response.status_code != 200:
            raise TestSuitePublishError(self._describe_failure(response, f"read the branch '{branch}'"))
        try:
            return response.json()["object"]["sha"]
        except (KeyError, TypeError, ValueError) as exc:
            raise TestSuitePublishError(f"GitHub returned an unexpected answer for the branch '{branch}'.") from exc

    def _commit_tree_sha(self, commit_sha: str) -> str:
        response = self._request("GET", "git", "commits", commit_sha)
        if response.status_code != 200:
            raise TestSuitePublishError(self._describe_failure(response, "read the base commit"))
        try:
            return response.json()["tree"]["sha"]
        except (KeyError, TypeError, ValueError) as exc:
            raise TestSuitePublishError("GitHub returned an unexpected answer for the base commit.") from exc

    def _remote_blobs(self, tree_sha: str) -> Dict[str, str]:
        """Every file in the base tree, as repository path to blob hash."""
        response = self._request("GET", "git", "trees", tree_sha, params={"recursive": "1"})
        if response.status_code != 200:
            raise TestSuitePublishError(self._describe_failure(response, "read the repository's files"))

        try:
            payload = response.json()
        except ValueError as exc:
            raise TestSuitePublishError("GitHub returned an unexpected answer for the repository's files.") from exc

        if payload.get("truncated"):
            # A partial listing would read as "the repository does not have
            # these files", and the push would delete them.
            raise TestSuitePublishError(
                "The repository is too large for its file list to be read in one request, "
                "so changes cannot be worked out safely."
            )

        return {
            item["path"]: item["sha"]
            for item in payload.get("tree", [])
            if item.get("type") == "blob" and item.get("path")
        }

    # -- planning and pushing --------------------------------------------

    def plan(
        self,
        suite_name: str,
        suite_directory: str,
        base_branch: str = "main",
        include_test_results: bool = False,
    ) -> PublishPlan:
        """
        Work out what pushing this suite would change on the base branch.

        Raises:
            TestSuitePublishError: the suite is empty, or GitHub could not be read
        """
        local_files = collect_suite_files(suite_directory, include_test_results=include_test_results)
        if not local_files:
            raise TestSuitePublishError("The suite directory holds no files to push.")

        base_commit_sha = self._branch_commit_sha(base_branch)
        base_tree_sha = self._commit_tree_sha(base_commit_sha)
        remote_blobs = self._remote_blobs(base_tree_sha)

        plan = PublishPlan(
            suite_name=suite_name,
            repository_url=self.repository_url,
            owner=self.owner,
            repo=self.repo,
            base_branch=base_branch,
            base_commit_sha=base_commit_sha,
            base_tree_sha=base_tree_sha,
        )

        local_paths = set()
        for suite_file in local_files:
            local_paths.add(suite_file.repo_path)
            remote_sha = remote_blobs.get(suite_file.repo_path)
            if remote_sha is None:
                plan.added.append(suite_file.repo_path)
            elif remote_sha != suite_file.blob_sha:
                plan.modified.append(suite_file.repo_path)
            else:
                plan.unchanged_count += 1
                continue

            plan.files_by_path[suite_file.repo_path] = suite_file
            plan.upload_bytes += suite_file.size

        plan.deleted = sorted(
            repo_path
            for repo_path in remote_blobs
            if repo_path not in local_paths and _is_tracked_repo_path(repo_path, include_test_results)
        )

        if plan.upload_bytes > MAX_TOTAL_UPLOAD_BYTES:
            raise TestSuitePublishError(
                f"The changed files come to more than {MAX_TOTAL_UPLOAD_BYTES // (1024 * 1024)} MB, "
                "which is too much for one push."
            )

        return plan

    def _create_blob(self, suite_file: SuiteFile) -> str:
        with open(suite_file.local_path, "rb") as handle:
            content = handle.read()

        response = self._request(
            "POST",
            "git",
            "blobs",
            json={"content": base64.b64encode(content).decode("ascii"), "encoding": "base64"},
        )
        if response.status_code != 201:
            raise TestSuitePublishError(
                self._describe_failure(response, f"upload '{suite_file.repo_path}'")
            )
        return response.json()["sha"]

    def publish(
        self,
        plan: PublishPlan,
        branch_name: str,
        commit_message: Optional[str] = None,
    ) -> Dict:
        """
        Create the branch and push the planned changes to it in one commit.

        Args:
            plan: What :meth:`plan` worked out against the base branch
            branch_name: The new branch to create; it must not already exist
            commit_message: Message for the commit, or None for a generated one

        Returns:
            What was pushed, with links to the branch and the commit

        Raises:
            TestSuitePublishError: the branch exists, there is nothing to push,
                or GitHub refused a step
        """
        branch_name = self._validate_branch(branch_name)

        if not plan.has_changes:
            raise TestSuitePublishError(
                f"The suite matches '{plan.base_branch}' already, so there is nothing to push."
            )

        if self.branch_exists(branch_name):
            raise TestSuitePublishError(f"The branch '{branch_name}' already exists in this repository.")

        tree_entries = []
        for repo_path in plan.added + plan.modified:
            suite_file = plan.files_by_path[repo_path]
            tree_entries.append(
                {
                    "path": repo_path,
                    "mode": GITHUB_FILE_MODE,
                    "type": "blob",
                    "sha": self._create_blob(suite_file),
                }
            )

        for repo_path in plan.deleted:
            # A null sha against a path in a tree built on the base tree is how
            # the Git data API records a deletion.
            tree_entries.append(
                {
                    "path": repo_path,
                    "mode": GITHUB_FILE_MODE,
                    "type": "blob",
                    "sha": None,
                }
            )

        tree_response = self._request(
            "POST",
            "git",
            "trees",
            json={"base_tree": plan.base_tree_sha, "tree": tree_entries},
        )
        if tree_response.status_code != 201:
            raise TestSuitePublishError(self._describe_failure(tree_response, "build the commit's file tree"))
        tree_sha = tree_response.json()["sha"]

        message = (commit_message or "").strip() or (
            f"Update test data and expected results for {plan.suite_name} "
            f"({len(plan.added)} added, {len(plan.modified)} changed, {len(plan.deleted)} removed)"
        )

        commit_response = self._request(
            "POST",
            "git",
            "commits",
            json={"message": message, "tree": tree_sha, "parents": [plan.base_commit_sha]},
        )
        if commit_response.status_code != 201:
            raise TestSuitePublishError(self._describe_failure(commit_response, "create the commit"))
        commit_sha = commit_response.json()["sha"]

        # Point the new branch straight at the finished commit: until this
        # succeeds nothing in the repository has changed.
        ref_response = self._request(
            "POST",
            "git",
            "refs",
            json={"ref": f"refs/heads/{branch_name}", "sha": commit_sha},
        )
        if ref_response.status_code != 201:
            raise TestSuitePublishError(
                self._describe_failure(ref_response, f"create the branch '{branch_name}'")
            )

        logger.info(
            "Pushed suite %s to %s/%s branch %s (%s added, %s changed, %s removed)",
            plan.suite_name,
            self.owner,
            self.repo,
            branch_name,
            len(plan.added),
            len(plan.modified),
            len(plan.deleted),
        )

        repository_html_url = f"https://github.com/{self.owner}/{self.repo}"
        result = plan.as_dict()
        result.update(
            {
                "success": True,
                "branch": branch_name,
                "commit_sha": commit_sha,
                "commit_message": message,
                "branch_url": f"{repository_html_url}/tree/{branch_name}",
                "commit_url": f"{repository_html_url}/commit/{commit_sha}",
                "compare_url": f"{repository_html_url}/compare/{plan.base_branch}...{branch_name}",
            }
        )
        return result
